### ISSUE TITLE
reset followed by addAll causing problems

### ISSUE THREAD

**Issue by profet23** [ndm2/ckeditor-placeholder-elements#4] opened 2015-09-14 21:35 UTC
It seems that issuing a 
```
editor.plugins.placeholder_elements.placeholders.reset();
```
following immediately by a 
```
editor.plugins.placeholder_elements.placeholders.addAll(newValues);
```
is causing some strangeness related to event handling. 

Placeholders are not getting highlighted/unhighlighted properly and such.

The workaround is to issue the above with a small delay:
```
editor.plugins.placeholder_elements.placeholders.reset();
window.setTimeout(function () {
     editor.plugins.placeholder_elements.placeholders.addAll(newValue);
}, 100);
```

This feels hacky though.

Maybe PlaceholdersCollection change events need to be queued and then combined into one even after changes have ceased for a period of time? If thats an acceptable solution, I'd be happy to issue a pull request.

**Comment by ndm2** [comment] 2015-09-14 22:09
Mmm, looks like this could be caused by `CKEditor.setData()` being async... before trying to work on workarounds, let's see if this can be fixed on a lower level.

**Comment by profet23** [comment] 2015-09-15 00:24
How do we feel about 7130fc335422d4b8a51cad948bf4122fac5ccc64

**Comment by ndm2** [comment] 2015-09-15 01:38
Looks like it could work, I'll look into it further tomorrow, or the day after, I have to fly away for now :airplane:

**Closed** 2015-09-17 14:37 UTC
Labels: bug
